--liquibase formatted sql

--changeset vlado:001-create-surface-type
CREATE TABLE surface_type
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted          BOOLEAN        NOT NULL DEFAULT FALSE,
    name             VARCHAR(50)    NOT NULL,
    price_per_minute DECIMAL(10, 2) NOT NULL,
    CONSTRAINT uk_surface_type_name UNIQUE (name)
);

--changeset vlado:002-create-customer
CREATE TABLE customer
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    phone_number VARCHAR(16) NOT NULL,
    name         VARCHAR(30) NOT NULL,
    CONSTRAINT uk_customer_phone_number UNIQUE (phone_number)
);

--changeset vlado:003-create-court
CREATE TABLE court
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE,
    court_number    VARCHAR(50) NOT NULL,
    surface_type_id BIGINT      NOT NULL,
    CONSTRAINT uk_court_number UNIQUE (court_number),
    CONSTRAINT fk_court_surface_type FOREIGN KEY (surface_type_id) REFERENCES surface_type (id)
);

--changeset vlado:004-create-reservation
CREATE TABLE reservation
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted     BOOLEAN        NOT NULL DEFAULT FALSE,
    court_id    BIGINT         NOT NULL,
    customer_id BIGINT         NOT NULL,
    start_time  TIMESTAMP      NOT NULL,
    end_time    TIMESTAMP      NOT NULL,
    game_type   VARCHAR(20)    NOT NULL,
    price       DECIMAL(10, 2) NOT NULL,
    created_at  TIMESTAMP      NOT NULL,
    CONSTRAINT fk_reservation_court FOREIGN KEY (court_id) REFERENCES court (id),
    CONSTRAINT fk_reservation_customer FOREIGN KEY (customer_id) REFERENCES customer (id)
);

--changeset vlado:005-create-reservation-indexes
CREATE INDEX idx_reservation_court_created_at ON reservation (court_id, created_at);
CREATE INDEX idx_reservation_customer_start_time ON reservation (customer_id, start_time);
CREATE INDEX idx_reservation_court_time ON reservation (court_id, start_time, end_time);